config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'articles', to: "articles#index"
  get 'articles/new', to: "articles#new"
  get 'articles/:id', to: "articles#show", as: :article
  post 'articles', to: "articles#create"
  get 'articles/:id/edit', to: "articles#edit", as: :article_update
  patch 'articles/:id', to: "articles#update"
  delete 'articles/:id', to: "articles#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update 
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <h1>Change this article</h1>
</div>
<div class="container">
  <%= form_for( @article ) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <% @articles.each do |article| %>
    <div class="article">
      <h1 class="title"> <%= link_to article.title, article_path(article) %> </h1>
      <p class="content"> <%= article.content %> </p>
    </div>
  <% end %>
</div>  

app/views/articles/new.html.erb
<div class="container">
  <h1>New article</h1>
</div>
<div class="container">
  <%= form_for( @article ) do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/articles/show.html.erb
<div class="container">
<h1>
  <%= @article.title  %>
  <%= link_to "🦄", article_update_path(@article) %>
  <%= link_to "💣", article_path(@article), method: "delete", data: { confirm: "Are you sure? This is a masterpiece"} %>
</h1>

<hr>
<p><%= @article.content %></p>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Wikinimous", articles_path, class:"navbar-brand" %>
      <%= link_to "Create new article", articles_new_path, class:"btn btn-outline-success my-2 my-sm-0"%>
    
    </nav>

    <%= yield %>
  </body>
</html>